language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: simon.menke@gmail.com
  api_key:
    secure: qP0VlfElrBSYD8srqNvnjBCTJH/7xk2RH4Q2DXqt8DR82WcZOaA9yv3+7UD+0LzQWwghwhpdpU9SKyvCkBDHFM3n2oQO4VUaq3dnI/NAue45br1mODtb+Srth/jwnfVP76LGqQRlKV2j7t0gfbBDq4H7hPX3ZKiOe4tI9oqkQhWtgXqRIMLN/urpr2YDlm72lHOn6pP3btVAeQQmfE4YU/WKK1kyyvEnTvRBK2yFDWGn42+2y4YR79E4Zc8RG6wFPdG9wNSSI2TDyRO4Jkvmf+LoJ0dezK5q68BbqOXaY8TKhtMiaD1SSdYuvt0+0TWJ14s30DubNyjiHH958ICN29HRnfwMyzSaNTiAb0uFS6ZMQSS8mCGsZiSDz7aGKK/WrUvtQvAWRHYS83Opv57xaJAUTIGtaPmzSv31/G1vDa7Q1X9ubllx0bsvF1DxtRwKjy+kT0o1DsnYsLjRIP2oLqEt6tJFUtOzxPzOY7a+k9E34lIikIWoc7GmKdLB/99JhwJm/fFDSdSlpetbGIPG/k2bi5oTql0MwutkzJQiq7YZ1FewXtvKKoCEPJnXdJBN+VPa9y8Yx6ArGCiAdazBB7SLnc5dHsai7v9vx27uCMmoeUGc2ulmWFsx+MDl+7qBDua5F+iL16iIvK2uTlVpdx+e/DJjGljaFSH2Ot5lujE=
  on:
    tags: true
    repo: fd/fh-core
